# Generated by Django 5.0.6 on 2024-05-16 12:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=5, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('max_persons', models.IntegerField(default=2)),
                ('room_type', models.CharField(choices=[('S', 'Single Occupancy'), ('D', 'Double Occupancy')], default=None, max_length=1)),
                ('price', models.IntegerField(default=500)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('guest_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255, null=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('last_name', models.CharField(max_length=255, null=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('phone', models.CharField(max_length=12, null=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='e-mail')),
                ('city', models.CharField(max_length=20, null=True)),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('checkIn', models.DateField()),
                ('checkOut', models.DateField()),
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_alloted', models.BooleanField(default=False)),
                ('accept', models.BooleanField(default=False)),
                ('reject', models.BooleanField(default=False)),
                ('guest', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='guest.guest')),
                ('room', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='guest.room')),
            ],
            options={
                'verbose_name_plural': 'Reservation',
            },
        ),
    ]
